// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATOKWOYvFX7rcB969S1yL9wl5KZizUByA',
    appId: '1:507601866903:web:8b5ab5569aa2dcf88ed9d2',
    messagingSenderId: '507601866903',
    projectId: 'orthotrade-d043b',
    authDomain: 'orthotrade-d043b.firebaseapp.com',
    storageBucket: 'orthotrade-d043b.appspot.com',
    measurementId: 'G-SQJ5W9HLVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfw6_GOqbKjDYlgNKd7BVbaWsh8epKXhM',
    appId: '1:507601866903:android:4578734a9ed7f6f48ed9d2',
    messagingSenderId: '507601866903',
    projectId: 'orthotrade-d043b',
    storageBucket: 'orthotrade-d043b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDcJjVcza0z2_PmMkRAteTKu9Yb6hQnu8',
    appId: '1:507601866903:ios:d26a472ec4ce0a328ed9d2',
    messagingSenderId: '507601866903',
    projectId: 'orthotrade-d043b',
    storageBucket: 'orthotrade-d043b.appspot.com',
    iosBundleId: 'com.example.orthotrade',
  );
}
